### ISSUE TITLE
Asking for more permissive license

### ISSUE THREAD

**Issue by Nevsden** [qu1x/kiss3d-trackball#2]
Dear author, 

I would really like to use your crate however as far as I am concerned, it does not allow me to make commercial use out of it.
Is there any chance you change the license?

Best,
nevsden

**Comment by n3vu0r** [comment]
Hi Nevsden,

this is already one of the most permissive licenses. It does allow commercial use. You don't have to publish your sources or any modifications you make to this crate. What other license do you have in mind?

**Comment by Nevsden** [comment]
Hi @n3vu0r, I have not much experience with the licences therefore did understand it incorrectly. Thank you for the clarification. The issue can therefore be closed.
